server:
  port: 8888
spring:
  application:
    name: ems
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456
    #redis
  redis:
    host: localhost
    port: 6379
    database: 0
    #静态资源放行
  resources:
    static-locations: classpath:/static/,file:${photo.dir}


mybatis:
  mapper-locations: classpath:com/xiaohe/mapper/*.xml
  type-aliases-package: com.xiaohe.entity
photo:
  dir: F:\mypracticeproject\ems\src\main\resources\static\photos

